"""Initial migration.

Revision ID: 706d382a1938
Revises: 2b3d88d537d2
Create Date: 2025-03-08 20:05:16.852747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706d382a1938'
down_revision = '2b3d88d537d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
